# Generated by Django 4.1.7 on 2023-03-13 19:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_alter_account_phone_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoginOtp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('otp', models.IntegerField()),
                ('is_used', models.BooleanField(default=False)),
                ('myuser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loginotp', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
