# Generated by Django 4.1.5 on 2023-02-20 08:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('patients', '0001_initial'),
        ('doctors', '0008_slot_booked_tokens'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('consultation_type', models.CharField(choices=[('online', 'Online'), ('offline', 'Offline')], max_length=10)),
                ('date_booked', models.DateField(auto_now_add=True)),
                ('time_booked', models.TimeField(auto_now_add=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patients.patientprofile')),
                ('slot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doctors.slot')),
            ],
        ),
    ]
