# Generated by Django 4.1.5 on 2023-04-03 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='canceled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='booking',
            name='refund',
            field=models.BooleanField(default=False),
        ),
    ]
