# Generated by Django 4.1.5 on 2023-04-03 09:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0001_initial'),
        ('doctors', '0001_initial'),
        ('booking', '0002_booking_canceled_booking_refund'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlockedSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blocked_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('blocked_token', models.IntegerField()),
                ('is_used', models.BooleanField(default=False)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patients.patientprofile')),
                ('slot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doctors.slot')),
            ],
        ),
    ]
