# Generated by Django 4.1.5 on 2023-04-05 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='slot',
            name='canceled',
            field=models.BooleanField(default=False),
        ),
    ]
