# Generated by Django 4.1.5 on 2023-02-10 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0002_alter_department_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='slug',
            field=models.SlugField(default='Physician', max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='department',
            name='name',
            field=models.CharField(default='Physician', max_length=255, unique=True),
        ),
    ]
