# Generated by Django 4.1.5 on 2023-02-13 13:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0006_remove_doctorprofile_is_approved'),
    ]

    operations = [
        migrations.AddField(
            model_name='slot',
            name='number_of_patients',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='qualification',
            name='doctor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='qualifications', to='doctors.doctorprofile'),
        ),
    ]
