# Generated by Django 4.1.5 on 2023-02-23 19:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0012_alter_doctorprofile_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctorprofile',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doctor_profile', to='doctors.department'),
        ),
    ]
